name: CI
on: [push, pull_request]
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester, PSScriptAnalyzer, PowerShellBuild
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Invoke-Pester -Path .\tests\Meta.tests.ps1
      - name: Test
        shell: pwsh
        run: ./build.ps1 -Task Test -Bootstrap
    # - uses: romeovs/lcov-reporter-action@v0.2.16
    #   with:
    #     lcov-file: ./coverage/lcov.info
